language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - mkdir $HOME/.python-eggs
  - chmod og-w $HOME/.python-eggs

install:
  - pip install flake8 sphinx
  - python setup.py develop

script:
  - flake8 artist
  - make -C demo test
  - sphinx-build -n doc doc/_build/html
